/**
 * Pure helpers shared by the LLM/AI Markdown endpoints.
 *
 * This module must stay free of app-only imports (e.g. `@/lib/source`) so it
 * can be unit tested in isolation.
 */

export const siteUrl = "https://docs.billwave.example";
export const openApiUrl = `${siteUrl}/openapi.json`;

export type LLMPage = {
  url: string;
  data: {
    title: string;
    description?: string;
    getText: (type: "raw" | "processed") => Promise<string>;
  };
};

export type ApiOperation = {
  method: string;
  path: string;
};

/** The `.md` URL for a docs page (e.g. `/getting-started/quickstart` -> `.md`). */
export function getPageMarkdownUrl(page: { url: string }): string {
  return page.url === "/" ? "/index.md" : `${page.url}.md`;
}

/** Resolve the slugs of a page from the URL segments of a `*.md` request. */
export function decodeMarkdownUrl(segments: string[]): string[] {
  const out = segments.filter(Boolean);
  if (out.at(-1) === "index") out.pop();
  return out;
}

/**
 * API-reference pages are generated by Fumadocs as `<APIPage ... />` with the
 * operation(s) in props. Extract them so we can render a useful Markdown
 * summary that points agents at the raw OpenAPI document.
 */
export function extractApiOperations(markdown: string): ApiOperation[] {
  const operations: ApiOperation[] = [];

  const read = (match: RegExpMatchArray | null, pathKey: "path" | "name") => {
    if (!match) return;
    try {
      const items = JSON.parse(match[1]) as Array<Record<string, unknown>>;
      for (const item of items) {
        const method = item?.method;
        const path = item?.[pathKey];
        if (typeof method === "string" && typeof path === "string") {
          operations.push({ method: method.toUpperCase(), path });
        }
      }
    } catch {
      // Ignore malformed props; the page still renders its description.
    }
  };

  read(markdown.match(/operations=\{(\[[\s\S]*?\])\}/), "path");
  read(markdown.match(/webhooks=\{(\[[\s\S]*?\])\}/), "name");

  return operations;
}

/** Render a single docs page as Markdown for LLMs and AI agents. */
export async function renderPageMarkdown(page: LLMPage): Promise<string> {
  const processed = await page.data.getText("processed");

  const operations = extractApiOperations(processed);

  const body = processed
    // Fumadocs' generated "do not edit" comment.
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, "")
    // The APIPage placeholder is replaced by the operations summary below.
    .replace(/<APIPage[\s\S]*?\/>/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  const apiSection =
    operations.length > 0
      ? `\n\n---\n\n## API operations\n\n${operations
          .map((op) => `- \`${op.method} ${op.path}\``)
          .join("\n")}\n\nFull request and response schemas: ${openApiUrl}\n`
      : "";

  return `# ${page.data.title} (${siteUrl}${page.url})\n\n${body}${apiSection}`;
}
