import { describe, expect, it } from "vitest";

import {
  decodeMarkdownUrl,
  extractApiOperations,
  getPageMarkdownUrl,
  openApiUrl,
  renderPageMarkdown,
} from "./llms-utils";

const generatedComment =
  "{/* This file was generated by Fumadocs. Do not edit this file directly. Any changes should be made by running the generation command again. */}";

describe("decodeMarkdownUrl", () => {
  it("keeps normal page slugs intact", () => {
    expect(decodeMarkdownUrl(["getting-started", "quickstart"])).toEqual([
      "getting-started",
      "quickstart",
    ]);
  });

  it("maps the index page to the root slugs", () => {
    expect(decodeMarkdownUrl(["index"])).toEqual([]);
  });

  it("ignores empty segments produced by splitting an empty splat", () => {
    expect(decodeMarkdownUrl([])).toEqual([]);
    expect(decodeMarkdownUrl([""])).toEqual([]);
    expect(decodeMarkdownUrl(["", "getting-started", "quickstart"])).toEqual([
      "getting-started",
      "quickstart",
    ]);
  });

  it("maps a folder index page to the folder root", () => {
    expect(decodeMarkdownUrl(["cli", "index"])).toEqual(["cli"]);
  });
});

describe("getPageMarkdownUrl", () => {
  it("uses index.md for the root page", () => {
    expect(getPageMarkdownUrl({ url: "/" })).toBe("/index.md");
  });

  it("appends .md to nested page URLs", () => {
    expect(getPageMarkdownUrl({ url: "/getting-started/quickstart" })).toBe(
      "/getting-started/quickstart.md",
    );
  });
});

describe("extractApiOperations", () => {
  it("reads operations from a generated APIPage placeholder", () => {
    const markdown = `${generatedComment}\n\nCreates a customer.\n\n<APIPage document={"./openapi.json"} operations={[{"path":"/v1/customers","method":"post"}]} />`;

    expect(extractApiOperations(markdown)).toEqual([
      { method: "POST", path: "/v1/customers" },
    ]);
  });

  it("reads webhook placeholders", () => {
    const markdown =
      '<APIPage document={"./openapi.json"} webhooks={[{"name":"charge.success","method":"post"}]} />';

    expect(extractApiOperations(markdown)).toEqual([
      { method: "POST", path: "charge.success" },
    ]);
  });

  it("returns nothing for prose pages", () => {
    expect(extractApiOperations("Just a normal page.")).toEqual([]);
  });

  it("does not throw on malformed props", () => {
    expect(
      extractApiOperations('<APIPage operations={[{"path":}]} />'),
    ).toEqual([]);
  });
});

describe("renderPageMarkdown", () => {
  it("renders prose pages with a canonical heading and source URL", async () => {
    const page = {
      url: "/getting-started/quickstart",
      data: {
        title: "Your first billing flow",
        getText: async () => "In this tutorial you will wire up a subscription.",
      },
    };

    const markdown = await renderPageMarkdown(page);

    expect(markdown).toBe(
      "# Your first billing flow (https://docs.billwave.example/getting-started/quickstart)\n\nIn this tutorial you will wire up a subscription.",
    );
  });

  it("replaces the APIPage placeholder with an operations summary and spec link", async () => {
    const page = {
      url: "/api-reference/createCustomer",
      data: {
        title: "Create or resolve a customer",
        getText: async () =>
          `${generatedComment}\n\nCreates a customer if needed.\n\n<APIPage document={"./openapi.json"} operations={[{"path":"/v1/customers","method":"post"}]} />`,
      },
    };

    const markdown = await renderPageMarkdown(page);

    expect(markdown).toContain("Creates a customer if needed.");
    expect(markdown).not.toContain("<APIPage");
    expect(markdown).not.toContain("generated by Fumadocs");
    expect(markdown).toContain("## API operations");
    expect(markdown).toContain("- `POST /v1/customers`");
    expect(markdown).toContain(openApiUrl);
  });

  it("does not add an API section to prose pages", async () => {
    const page = {
      url: "/pricing/plans",
      data: {
        title: "Plans & products",
        getText: async () => "Plans and products explained.",
      },
    };

    const markdown = await renderPageMarkdown(page);

    expect(markdown).not.toContain("## API operations");
  });
});
